window.CONFIG = {
    // YouTube Data API v3 の本物のAPIキーをダブルクォーテーションの中に貼り付けてください
    YOUTUBE_API_KEY: "AIzaSyDoy4uvy_4jXcpGw8fxTE33lFmBn18fAYY",
    // キャッシュ有効期間（ミリ秒）。デフォルト5分。
    CACHE_DURATION_MS: 300000,
    // チャンネルアイコンのキャッシュ有効期間（ミリ秒）。デフォルト24時間。
    CHANNEL_ICON_CACHE_DURATION_MS: 86400000,
    DEFAULT_CHANNELS: [
        {
                "name": "まぐにぃ",
                "id": "UCMP7QuS4suoONg47Nbi-wrg",
                "minecraftId": "maguro29",
                "uuid": "482e3dfc-7bea-4afa-96a7-9ff6f549996c",
                "twitterId": "maguro29",
                "twitchId": "maguro29game",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "https://discord.gg/bRuT74X7sS",
                "homepageUrl": "https://maguro29info.netlify.app/",
                "color": "#2bff00",
                "avatarImg": "avatars/maguro29.svg"
        },
        {
                "name": "じゃじゃーん菊池",
                "id": "UCi2kiw8hMo0vMAh5lXiafug",
                "minecraftId": "jajaankikuchi",
                "uuid": "563bd621-fd52-4a24-946d-aa8d199d3ecc",
                "twitterId": "kikuchidaisuke",
                "twitchId": "",
                "tiktokId": "jajakiku",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "https://lit.link/jajakiku",
                "color": "#ffa200",
                "avatarImg": "avatars/jajaankikuchi.svg"
        },
        {
                "name": "さかいさんだー",
                "id": "UCuk8ABJTVWiApYlEojW_QrA",
                "minecraftId": "Sakai_Thunder",
                "uuid": "77ca6cbf-3fbf-4bf7-8624-87044bb7c663",
                "twitterId": "Sakai_Thunder",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "https://lit.link/sakaithunder",
                "color": "#11e4d6",
                "avatarImg": "avatars/Sakai_Thunder.svg"
        },
        {
                "name": "Ｍさん",
                "id": "UCGK0iFuXhfA5VnL64xiKEmQ",
                "minecraftId": "MrMsan",
                "uuid": "fe91adf4-7131-4da5-bcbf-b4a675d4ceef",
                "twitterId": "maikura_souti",
                "twitchId": "msan_no_nitizyou",
                "tiktokId": "msan_official",
                "instaId": "",
                "discordUrl": "",
                "color": "#00ffff",
                "avatarImg": "avatars/MrMsan.svg"
        },
        {
                "name": "タツナミ先生",
                "id": "UCedenULTLYf3DanflEXdRCQ",
                "minecraftId": "shyutan",
                "uuid": "1d0e9619-9d02-4925-b49e-220ce08aaf6e",
                "twitterId": "tatsunami",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "",
                "color": "#080808",
                "avatarImg": "avatars/shyutan.svg"
        },
        {
                "name": "神近",
                "id": "UCdLe2q91fJkN9GEyDvItp-w",
                "minecraftId": "kamichika",
                "uuid": "f06cbdea-3f49-48ec-a9ca-39beade0e990",
                "twitterId": "t_kamichika",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#f59324",
                "avatarImg": "avatars/kamichika.svg"
        },
        {
                "name": "しろくる",
                "id": "UCTl5XpFddyDsj5woStUPu0w",
                "minecraftId": "sirokuru",
                "uuid": "a6bc0a31-4641-44b5-af3f-4350c89528d4",
                "twitterId": "sirokuru_",
                "twitchId": "sirokuru",
                "tiktokId": "sirokuru",
                "instaId": "",
                "discordUrl": "",
                "color": "#ffffff",
                "avatarImg": "avatars/sirokuru.svg"
        },
        {
                "name": "たにし",
                "id": "UCiC8VCiSLD3mxoO-QFKQnBQ",
                "minecraftId": "Tanish1",
                "uuid": "939aa8b1-7e6c-458b-9c25-af2a5e7becc0",
                "twitterId": "tanishi_manbo",
                "twitchId": "tanishi1200",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#00ff7b",
                "avatarImg": "avatars/Tanish1.svg"
        },
        {
                "name": "凸もり",
                "id": "UCdN9GjPrqhcrzE27eWNNjxg",
                "minecraftId": "totsumori",
                "uuid": "e7312231-f09f-4b02-b71b-cefb5a4d87b1",
                "twitterId": "mk_2_totsu",
                "twitchId": "totsumori",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#888888",
                "avatarImg": "avatars/totsumori.svg"
        },
        {
                "name": "神宮寺ちゃんねる",
                "id": "UCou8IVB8jJPk56H0farYQdA",
                "minecraftId": "jingujich",
                "uuid": "9944cd57-19b4-4516-a232-48a6b6ec9f25",
                "twitterId": "jinguji777ch",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#00bfff",
                "avatarImg": "avatars/jingujich.svg"
        },
        {
                "name": "カズクラ",
                "id": "UCu3Mp1ZimtNvyA-bcfo9VrQ",
                "minecraftId": "kazuchannel",
                "uuid": "c85613bd-c3b6-43ea-8a12-a9649fa769b0",
                "twitterId": "kazuch0924",
                "twitchId": "",
                "tiktokId": "super_kazukura",
                "instaId": "kazuch0924",
                "discordUrl": "",
                "color": "#ff0000",
                "avatarImg": "avatars/kazuchannel.svg"
        },
        {
                "name": "たいたい",
                "id": "UCds-nvoKCcvixVXJ_54QcbQ",
                "minecraftId": "taitai0904",
                "uuid": "65620d1a-889e-407f-9b0a-cfbb579f8963",
                "twitterId": "taitaiMEN1997",
                "twitchId": "taitai19970904",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ffdd00",
                "avatarImg": "avatars/taitai0904.svg"
        },
        {
                "name": "岐阜のこみちん",
                "id": "UCw4frqkotySLjJ_CFZR5-7w",
                "minecraftId": "komichin",
                "uuid": "81cb4bb1-5ba8-4a63-bdbe-570dccdf8ec2",
                "twitterId": "komichin0704",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "https://www.komichin.com/",
                "color": "#ff1100",
                "avatarImg": "avatars/komichin.svg"
        },
        {
                "name": "ナナホシナナ",
                "id": "UCncsOsnMBAAaYb6WidBYIDw",
                "minecraftId": "nanahoshiNanaVT",
                "uuid": "a5ef6ef3-9cf1-4c05-ab1f-7c47d13f6d06",
                "twitterId": "nanahoshinana77",
                "twitchId": "nanahoshinana77",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "https://lit.link/nanahoshinana77",
                "color": "#ff333d",
                "avatarImg": "avatars/nanahoshiNanaVT.svg"
        },
        {
                "name": "月成るくす",
                "id": "UCP9rcDSyTRtnu8EsG2CmLMg",
                "minecraftId": "tsukinarilux",
                "uuid": "00fdc6a9-b63d-4456-86e5-271c91645cd9",
                "twitterId": "Tsukinari_Lux_",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "tsukinarilux",
                "discordUrl": "",
                "homepageUrl": "https://tsukinarilux.wixsite.com/tsukinarilux",
                "color": "#bcec55",
                "avatarImg": "avatars/tsukinarilux.svg"
        },
        {
                "name": "メッス",
                "id": "UCkJeBcOPRBs5bri5B3sFgVg",
                "minecraftId": "messu009",
                "uuid": "2d610d25-8c20-44d9-97ae-21f3212a401e",
                "twitterId": "messu_009",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ffffff",
                "avatarImg": "avatars/messu009.svg"
        },
        {
                "name": "よいよい",
                "id": "UCzk-vAIbo3iVBGTNaJQS2qQ",
                "minecraftId": "yoiy0i",
                "uuid": "273c51d0-3e15-4445-8db9-1f4606e68dfe",
                "twitterId": "yoiy0i",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ff0000",
                "avatarImg": "avatars/yoiy0i.svg"
        },
        {
                "name": "うえまさ",
                "id": "UCIBDdDXnViOgN5tCpfX7NOA",
                "minecraftId": "uema5a",
                "uuid": "8b519650-3606-4e81-8c7a-5db5d00a9f95",
                "twitterId": "uema5aCh",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "uema5a",
                "discordUrl": "https://discord.com/invite/kprgJGmSJ9",
                "homepageUrl": "",
                "color": "#0008ff",
                "avatarImg": "avatars/uema5a.svg"
        },
        {
                "name": "久那式リン",
                "id": "UCPs7s2VlkwVWWpjcyjviINA",
                "minecraftId": "Kunashiki_Lin",
                "uuid": "445a1617-cc6f-49b0-be6d-a102c5dcdf33",
                "twitterId": "Kunashiki_Lin_",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "discord.gg/ZwZ8nrecY",
                "homepageUrl": "https://frontier.creatia.cc/fanclubs/4124",
                "color": "#afebf3",
                "avatarImg": "avatars/Kunashiki_Lin.svg"
        },
        {
                "name": "珍珠花こまり",
                "id": "UCSLCZ5uhCYUMQ9TG9Cs1ERQ",
                "minecraftId": "yukiyanagiKOMARI",
                "uuid": "eab1fd9e-92b4-4594-86b0-5c4b6f00c520",
                "twitterId": "komari_yuki",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "https://lethalplan.booth.pm/",
                "color": "#ffe5e5",
                "avatarImg": "avatars/yukiyanagiKOMARI.svg"
        },
        {
                "name": "ぽこにゃん",
                "id": "UCO06KZjWOe6b1tXrgzzakZA",
                "minecraftId": "pokonyan_0603",
                "uuid": "b1531516-40ac-46b1-baf9-5d2db7a44dca",
                "twitterId": "pokonyan1185",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#00ff00",
                "avatarImg": "avatars/pokonyan_0603.svg"
        },
        {
                "name": "KtR（こーたろー）",
                "id": "UCuJVrV6spfu9QUP6Wr4fugA",
                "minecraftId": "HAOgame_KtR",
                "uuid": "54bd9568-8858-46e4-9d6b-1d94779ffd0f",
                "twitterId": "HAOKtR",
                "twitchId": "haoch_ktr",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "https://lit.link/haochktr",
                "color": "#ff3333",
                "avatarImg": "avatars/HAOgame_KtR.svg"
        },
        {
                "name": "ゆりも",
                "id": "UCrfGCEk3MPYap72t0TX_sdQ",
                "minecraftId": "yurimosaaan",
                "uuid": "0e6b9c2a-560a-4593-b0c0-983ecb209c4f",
                "twitterId": "yurimotosuzu",
                "twitchId": "yurimotosuzu",
                "tiktokId": "yurimotosuzu",
                "instaId": "yurimotosuzu",
                "discordUrl": "",
                "homepageUrl": "",
                "color": "#cbeccd",
                "avatarImg": "avatars/yurimosaaan.svg"
        },
        {
                "name": "むっこ氏",
                "id": "UCZf78JzSJj9mDQOBIr4mPqg",
                "minecraftId": "mukkoman",
                "uuid": "4d72d173-dc5e-4e31-b913-eda903e260b2",
                "twitterId": "mukkkkko",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "",
                "color": "#eec8d6",
                "avatarImg": "avatars/mukkoman.svg"
        },
        {
                "name": "うが",
                "id": "UCPqrIvS6LYOXa348ZucLDAg",
                "minecraftId": "uga_youtube",
                "uuid": "ed38df6a-3374-4ba4-ae36-1de9a049447d",
                "twitterId": "uga_totemuman",
                "twitchId": "",
                "tiktokId": "uga_youtube",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "lit.link/uga_totemuman",
                "color": "#e8c99c",
                "avatarImg": "avatars/uga_youtube.svg"
        },
        {
                "name": "鶴太郎",
                "id": "UC44DZLHQJOW-of5m5XZunLQ",
                "minecraftId": "turu0004",
                "uuid": "ffe0bac5-b1d5-42e8-9f74-6e7ba8668fdc",
                "twitterId": "turu0005",
                "twitchId": "turu0005",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "",
                "color": "#ffffff",
                "avatarImg": "avatars/turu0004.svg"
        },
        {
                "name": "LeftLily / レフトリリー",
                "id": "UC2Oi_Pfzk-G3HyhnbP5vJLA",
                "minecraftId": "LeftLily0427",
                "uuid": "554d4e40-a120-4889-a8f3-933938e6cc1c",
                "twitterId": "Leftsunmoon",
                "twitchId": "left_sun",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "",
                "color": "#2bff00",
                "avatarImg": "avatars/LeftLily0427.svg"
        },
        {
                "name": "イリクス学園/久遠星那",
                "id": "UC-jJgNH2jX-I6eyXoOuLfAg",
                "minecraftId": "kuon_irix",
                "uuid": "1d1a367d-27ef-4ca0-b5b0-c202fe0f6761",
                "twitterId": "KuonSena",
                "twitchId": "kuon_sena",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "https://marshmallow-qa.com/aqthmqecmscaggr?t=fbfYpm&utm_medium=url_text&utm_source=promotion",
                "color": "#a600ff",
                "avatarImg": "avatars/kuon_irix.svg"
        },
        {
                "name": "早乙女燈真 / Saotome Touma",
                "id": "UCGSNOUcXKZ5IFYJLycyHR2A",
                "minecraftId": "saotomeirix",
                "uuid": "b039c461-602b-42f0-9283-ac9e35083ad0",
                "twitterId": "SaotomeTouma",
                "twitchId": "saotome_touma",
                "tiktokId": "saotometouma",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "",
                "color": "#f8b9f6",
                "avatarImg": "avatars/saotomeirix.svg"
        },
        {
                "name": "黎乃鈴 -Kurono Suzu-",
                "id": "UCvq_7I63tALUzJJvFOrjHPg",
                "minecraftId": "kuronosuzu",
                "uuid": "200306b6-40e3-4b30-9b44-d5aa0d1c2b8f",
                "twitterId": "黎乃鈴 -Kurono Suzu-",
                "twitchId": "rag_suzu",
                "tiktokId": "rag_suzu",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "",
                "color": "#df96e8",
                "avatarImg": "avatars/kuronosuzu.svg"
        },
        {
                "name": "28（ふたば）Games",
                "id": "UCpONKlVEdkBeKsE1hlPvrfg",
                "minecraftId": "ftb28",
                "uuid": "a2bdc570-3b2c-464a-9c38-e9a681c0d506",
                "twitterId": "28ftb_sub",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "",
                "color": "#ff9900",
                "avatarImg": "avatars/ftb28.svg"
        },
        {
                "name": "UDON",
                "id": "UC8WvsghW1a2JUIuHBu8qz7w",
                "minecraftId": "UDON130",
                "uuid": "1065ce22-9f3a-4ce6-ac18-063be1411086",
                "twitterId": "UDON130",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "",
                "color": "#ffea00",
                "avatarImg": "avatars/UDON130.svg"
        },
        {
                "name": "よし",
                "id": "UCFkfHzxpDGEDAjsg34tKu_g",
                "minecraftId": "yoshi_38_",
                "uuid": "17376ad0-a16a-4b66-85de-1a133bafb2bf",
                "twitterId": "yoshi38_dog",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "homepageUrl": "",
                "color": "#ff9900",
                "avatarImg": "avatars/yoshi_38_.svg"
        }
]
};
