window.CONFIG = {
    // キャッシュ有効期間（ミリ秒）。デフォルト5分。
    CACHE_DURATION_MS: 5 * 60 * 1000,
    // チャンネルアイコンのキャッシュ有効期間（ミリ秒）。デフォルト24時間。
    CHANNEL_ICON_CACHE_DURATION_MS: 24 * 60 * 60 * 1000,
    // YouTube Data API v3 の本物のAPIキーをダブルクォーテーションの中に貼り付けてください
    YOUTUBE_API_KEY: "AIzaSyDoy4uvy_4jXcpGw8fxTE33lFmBn18fAYY",
    DEFAULT_CHANNELS: [
        {
                "name": "まぐにぃ",
                "id": "UCMP7QuS4suoONg47Nbi-wrg",
                "minecraftId": "maguro29",
                "uuid": "482e3dfc-7bea-4afa-96a7-9ff6f549996c",
                "twitterId": "maguro29",
                "twitchId": "maguro29game",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "https://discord.gg/bRuT74X7sS",
                "color": "#2bff00",
                "avatarImg": "avatars/maguro29.svg",
                "homepageUrl": ""
        },
        {
                "name": "じゃじゃーん菊池",
                "id": "UCi2kiw8hMo0vMAh5lXiafug",
                "minecraftId": "jajaankikuchi",
                "uuid": "563bd621-fd52-4a24-946d-aa8d199d3ecc",
                "twitterId": "kikuchidaisuke",
                "twitchId": "",
                "tiktokId": "jajakiku",
                "instaId": "",
                "discordUrl": "",
                "color": "#ffa200",
                "avatarImg": "avatars/jajaankikuchi.svg",
                "homepageUrl": ""
        },
        {
                "name": "さかいさんだー",
                "id": "UCuk8ABJTVWiApYlEojW_QrA",
                "minecraftId": "Sakai_Thunder",
                "uuid": "77ca6cbf-3fbf-4bf7-8624-87044bb7c663",
                "twitterId": "Sakai_Thunder",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ff00ff",
                "avatarImg": "avatars/Sakai_Thunder.svg",
                "homepageUrl": ""
        },
        {
                "name": "Ｍさん",
                "id": "UCGK0iFuXhfA5VnL64xiKEmQ",
                "minecraftId": "MrMsan",
                "uuid": "fe91adf4-7131-4da5-bcbf-b4a675d4ceef",
                "twitterId": "maikura_souti",
                "twitchId": "msan_no_nitizyou",
                "tiktokId": "msan_official",
                "instaId": "",
                "discordUrl": "",
                "color": "#00ffff",
                "avatarImg": "avatars/MrMsan.svg",
                "homepageUrl": ""
        },
        {
                "name": "タツナミ先生",
                "id": "UCedenULTLYf3DanflEXdRCQ",
                "minecraftId": "syuutan",
                "uuid": "a73d2578-4b8d-4c9d-a552-aca11f93aa27",
                "twitterId": "tatsunami",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#00ff00",
                "avatarImg": "avatars/syuutan.svg",
                "homepageUrl": ""
        },
        {
                "name": "神近",
                "id": "UCdLe2q91fJkN9GEyDvItp-w",
                "minecraftId": "kamichika",
                "uuid": "f06cbdea-3f49-48ec-a9ca-39beade0e990",
                "twitterId": "t_kamichika",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#f59324",
                "avatarImg": "avatars/kamichika.svg",
                "homepageUrl": ""
        },
        {
                "name": "しろくる",
                "id": "UCTl5XpFddyDsj5woStUPu0w",
                "minecraftId": "sirokuru",
                "uuid": "a6bc0a31-4641-44b5-af3f-4350c89528d4",
                "twitterId": "sirokuru_",
                "twitchId": "sirokuru",
                "tiktokId": "sirokuru",
                "instaId": "",
                "discordUrl": "",
                "color": "#ffffff",
                "avatarImg": "avatars/sirokuru.svg",
                "homepageUrl": ""
        },
        {
                "name": "たにし",
                "id": "UCiC8VCiSLD3mxoO-QFKQnBQ",
                "minecraftId": "Tanish1",
                "uuid": "939aa8b1-7e6c-458b-9c25-af2a5e7becc0",
                "twitterId": "tanishi_manbo",
                "twitchId": "tanishi1200",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#00ff7b",
                "avatarImg": "avatars/Tanish1.svg",
                "homepageUrl": ""
        },
        {
                "name": "凸もり",
                "id": "UCdN9GjPrqhcrzE27eWNNjxg",
                "minecraftId": "totsumori",
                "uuid": "e7312231-f09f-4b02-b71b-cefb5a4d87b1",
                "twitterId": "mk_2_totsu",
                "twitchId": "totsumori",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#888888",
                "avatarImg": "avatars/totsumori.svg",
                "homepageUrl": ""
        },
        {
                "name": "神宮寺ちゃんねる",
                "id": "UCou8IVB8jJPk56H0farYQdA",
                "minecraftId": "jingujich",
                "uuid": "9944cd57-19b4-4516-a232-48a6b6ec9f25",
                "twitterId": "jinguji777ch",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#00bfff",
                "avatarImg": "avatars/jingujich.svg",
                "homepageUrl": ""
        },
        {
                "name": "カズクラ",
                "id": "UCu3Mp1ZimtNvyA-bcfo9VrQ",
                "minecraftId": "kazuchannel",
                "uuid": "c85613bd-c3b6-43ea-8a12-a9649fa769b0",
                "twitterId": "kazuch0924",
                "twitchId": "",
                "tiktokId": "super_kazukura",
                "instaId": "kazuch0924",
                "discordUrl": "",
                "color": "#ff0000",
                "avatarImg": "avatars/kazuchannel.svg",
                "homepageUrl": ""
        },
        {
                "name": "たいたい",
                "id": "UCds-nvoKCcvixVXJ_54QcbQ",
                "minecraftId": "taitai0904",
                "uuid": "65620d1a-889e-407f-9b0a-cfbb579f8963",
                "twitterId": "taitaiMEN1997",
                "twitchId": "taitai19970904",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ffdd00",
                "avatarImg": "avatars/taitai0904.svg",
                "homepageUrl": ""
        },
        {
                "name": "岐阜のこみちん",
                "id": "UCw4frqkotySLjJ_CFZR5-7w",
                "minecraftId": "komichin",
                "uuid": "81cb4bb1-5ba8-4a63-bdbe-570dccdf8ec2",
                "twitterId": "komichin0704",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ffcc00",
                "avatarImg": "avatars/komichin.svg",
                "homepageUrl": ""
        },
        {
                "name": "ナナホシナナ",
                "id": "UCncsOsnMBAAaYb6WidBYIDw",
                "minecraftId": "nanahoshiNanaVT",
                "uuid": "a5ef6ef3-9cf1-4c05-ab1f-7c47d13f6d06",
                "twitterId": "nanahoshinana77",
                "twitchId": "nanahoshinana77",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ff33ff",
                "avatarImg": "avatars/nanahoshiNanaVT.svg",
                "homepageUrl": ""
        },
        {
                "name": "月成るくす",
                "id": "UCP9rcDSyTRtnu8EsG2CmLMg",
                "minecraftId": "tsukinarilux",
                "uuid": "00fdc6a9-b63d-4456-86e5-271c91645cd9",
                "twitterId": "Tsukinari_Lux_",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "tsukinarilux",
                "discordUrl": "",
                "color": "#bcec55",
                "avatarImg": "avatars/tsukinarilux.svg",
                "homepageUrl": ""
        },
        {
                "name": "メッス",
                "id": "UCkJeBcOPRBs5bri5B3sFgVg",
                "minecraftId": "messu009",
                "uuid": "2d610d25-8c20-44d9-97ae-21f3212a401e",
                "twitterId": "messu_009",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ffffff",
                "avatarImg": "avatars/messu009.svg",
                "homepageUrl": ""
        },
        {
                "name": "よいよい",
                "id": "UCzk-vAIbo3iVBGTNaJQS2qQ",
                "minecraftId": "yoiy0i",
                "uuid": "273c51d0-3e15-4445-8db9-1f4606e68dfe",
                "twitterId": "yoiy0i",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ff0000",
                "avatarImg": "avatars/yoiy0i.svg",
                "homepageUrl": ""
        },
        {
                "name": "うえまさ",
                "id": "UCIBDdDXnViOgN5tCpfX7NOA",
                "minecraftId": "uema5a",
                "uuid": "8b519650-3606-4e81-8c7a-5db5d00a9f95",
                "twitterId": "uema5aCh",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "uema5a",
                "discordUrl": "",
                "color": "#0008ff",
                "avatarImg": "avatars/uema5a.svg",
                "homepageUrl": ""
        },
        {
                "name": "久那式リン",
                "id": "UCPs7s2VlkwVWWpjcyjviINA",
                "minecraftId": "Kunashiki_Lin",
                "uuid": "445a1617-cc6f-49b0-be6d-a102c5dcdf33",
                "twitterId": "Kunashiki_Lin_",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "https://discord.gg/ZwZ8nrecY",
                "color": "#afebf3",
                "avatarImg": "avatars/Kunashiki_Lin.svg",
                "homepageUrl": ""
        },
        {
                "name": "犬野はる",
                "id": "UCVB16vOi24WElLNbbmOFFsA",
                "minecraftId": "INUNOHARU",
                "uuid": "a5290981-1db7-4b75-a6ca-aeb8c6831036",
                "twitterId": "VT_InunoHaru",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ccffcc",
                "avatarImg": "avatars/INUNOHARU.svg",
                "homepageUrl": ""
        },
        {
                "name": "珍珠花こまり",
                "id": "UCSLCZ5uhCYUMQ9TG9Cs1ERQ",
                "minecraftId": "yukiyanagiKOMARI",
                "uuid": "eab1fd9e-92b4-4594-86b0-5c4b6f00c520",
                "twitterId": "komari_yuki",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ffe5e5",
                "avatarImg": "avatars/yukiyanagiKOMARI.svg",
                "homepageUrl": ""
        },
        {
                "name": "ぽこにゃん",
                "id": "UCO06KZjWOe6b1tXrgzzakZA",
                "minecraftId": "pokonyan_0603",
                "uuid": "b1531516-40ac-46b1-baf9-5d2db7a44dca",
                "twitterId": "pokonyan1185",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#00ff00",
                "avatarImg": "avatars/pokonyan_0603.svg",
                "homepageUrl": ""
        },
        {
                "name": "KtR（こーたろー）",
                "id": "UCuJVrV6spfu9QUP6Wr4fugA",
                "minecraftId": "HAOgame_KtR",
                "uuid": "54bd9568-8858-46e4-9d6b-1d94779ffd0f",
                "twitterId": "HAOKtR",
                "twitchId": "haoch_ktr",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ff3333",
                "avatarImg": "avatars/HAOgame_KtR.svg",
                "homepageUrl": ""
        },
        {
                "name": "桜咲千依",
                "id": "UCynBu4jMSaOLQ8OSQMowP1g",
                "minecraftId": "chiyohamstar",
                "uuid": "e5b5cc65-6173-4dc9-907c-df8c7a37273d",
                "twitterId": "chiyosab22",
                "twitchId": "",
                "tiktokId": "",
                "instaId": "",
                "discordUrl": "",
                "color": "#ffffff",
                "avatarImg": "avatars/chiyohamstar.svg",
                "homepageUrl": ""
        },
        {
                "name": "ゆりも",
                "id": "UCrfGCEk3MPYap72t0TX_sdQ",
                "minecraftId": "yurimosaaan",
                "uuid": "0e6b9c2a-560a-4593-b0c0-983ecb209c4f",
                "twitterId": "yurimotosuzu",
                "twitchId": "yurimotosuzu",
                "tiktokId": "yurimotosuzu",
                "instaId": "",
                "discordUrl": "",
                "color": "#aae4d3",
                "avatarImg": "avatars/yurimosaaan.svg",
                "homepageUrl": ""
        }
]
};
